<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Project', 'doctrine');

/**
 * BaseProject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idproject
 * @property string $name
 * @property Doctrine_Collection $Text
 * 
 * @method integer             getIdproject() Returns the current record's "idproject" value
 * @method string              getName()      Returns the current record's "name" value
 * @method Doctrine_Collection getText()      Returns the current record's "Text" collection
 * @method Project             setIdproject() Sets the current record's "idproject" value
 * @method Project             setName()      Sets the current record's "name" value
 * @method Project             setText()      Sets the current record's "Text" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project');
        $this->hasColumn('idproject', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 64,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Text', array(
             'local' => 'idproject',
             'foreign' => 'idproject'));
    }
}