<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Language', 'doctrine');

/**
 * BaseLanguage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idlang
 * @property string $descriptor
 * 
 * @method integer  getIdlang()     Returns the current record's "idlang" value
 * @method string   getDescriptor() Returns the current record's "descriptor" value
 * @method Language setIdlang()     Sets the current record's "idlang" value
 * @method Language setDescriptor() Sets the current record's "descriptor" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLanguage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('language');
        $this->hasColumn('idlang', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('descriptor', 'string', 2, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}