<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Text', 'doctrine');

/**
 * BaseText
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtext
 * @property string $paragraph
 * @property boolean $app
 * @property boolean $web
 * @property string $destinationfile
 * @property boolean $status
 * @property integer $idproject
 * @property timestamp $created
 * @property timestamp $updated
 * @property Project $Project
 * 
 * @method integer   getIdtext()          Returns the current record's "idtext" value
 * @method string    getParagraph()       Returns the current record's "paragraph" value
 * @method boolean   getApp()             Returns the current record's "app" value
 * @method boolean   getWeb()             Returns the current record's "web" value
 * @method string    getDestinationfile() Returns the current record's "destinationfile" value
 * @method boolean   getStatus()          Returns the current record's "status" value
 * @method integer   getIdproject()       Returns the current record's "idproject" value
 * @method timestamp getCreated()         Returns the current record's "created" value
 * @method timestamp getUpdated()         Returns the current record's "updated" value
 * @method Project   getProject()         Returns the current record's "Project" value
 * @method Text      setIdtext()          Sets the current record's "idtext" value
 * @method Text      setParagraph()       Sets the current record's "paragraph" value
 * @method Text      setApp()             Sets the current record's "app" value
 * @method Text      setWeb()             Sets the current record's "web" value
 * @method Text      setDestinationfile() Sets the current record's "destinationfile" value
 * @method Text      setStatus()          Sets the current record's "status" value
 * @method Text      setIdproject()       Sets the current record's "idproject" value
 * @method Text      setCreated()         Sets the current record's "created" value
 * @method Text      setUpdated()         Sets the current record's "updated" value
 * @method Text      setProject()         Sets the current record's "Project" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseText extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('text');
        $this->hasColumn('idtext', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('paragraph', 'string', 650, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 650,
             ));
        $this->hasColumn('app', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('web', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('destinationfile', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('idproject', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'idproject',
             'foreign' => 'idproject'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'paragraph',
              1 => 'status',
             ),
             ));
        $this->actAs($i18n0);
    }
}