<?php

/**
 * LanguageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LanguageTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object LanguageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Language');
    }

    /**
     * Devuelve todos los lenguajes
     * 
     * @return array
     */
    public static function get()
    {
        $q = Doctrine::getTable('Language')
                ->createQuery('lang')
                ->orderBy('lang.descriptor');
        return $q->fetchArray();
    }

    /**
     * Devuelve todos los lenguajes formateados por nombre
     * 
     * @return array
     */
    public static function getAll() 
    {
        $allLanguages = Doctrine_Query::create()->from('Language l')->orderBy('l.descriptor')->execute();
        $languages = array();
        foreach ($allLanguages as $language) {
            $languages[$language->getIdlang()] = $language->getDescriptor();
        }
        return $languages;
    }

    /**
     * Devuelve el nombre del idioma
     * 
     * @param integer $id
     */
    public static function getName($id) 
    {
        return Doctrine_Core::getTable('Language')->find($id)->getDescriptor();
    }

    /**
     * Devuelve el número de traducciones
     * 
     * @param integer $id
     * @return array
     */
    public static function getCount($id) 
    {
        $culture = self::getNameLanguage($id);
        $con = Doctrine_Manager::getInstance()->connection();
        $sql = "SELECT count(idtext) FROM text_translation WHERE lang='" . $culture . "' GROUP BY lang";
        return $con->execute($sql)->fetch();
    }

}