<?php

/**
 * ProjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ProjectTable
     */
    public static function getInstance() 
    {
        return Doctrine_Core::getTable('Project');
    }

    /**
     * Devuelve todos los proyectos
     * @return array
     */
    public static function getAll() 
    {
        $allProjects = Doctrine_Query::create()->from('project p')->orderBy('p.name')->execute();
        $projects = array();
        foreach ($allProjects as $project) {
            $projects[$project->getIdProject()] = $project->getName();
        }
        return $projects;
    }

    /**
     * Devuelve el número de traducciones asignadas por proyecto.
     * 
     * @param integer $id
     * @return array
     */
    public function getCount($id) 
    {
        $q = Doctrine_Query::create()
                ->select('COUNT(t.idtext) as numTexts')
                ->from('text t')
                ->where('t.idproject = ?', $id);
        return $q->fetchOne();
    }

}