# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    ['http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css', main.css, tipTip.css]

  javascripts:    ['http://code.jquery.com/jquery-1.9.1.js','jquery.tipTip.minified.js', 'http://code.jquery.com/ui/1.10.3/jquery-ui.js',  'main.js']

  has_layout:     true
  layout:         layout
