generator:
  class: sfDoctrineGenerator
  param:
    model_class:           text
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          text
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        idproject: { label: Project }
      list:
      filter:  ~
      form:    ~
      edit:    
        actions:
          _save: ~
      new:     
        actions:
          _save_and_add: ~
