Language:
  connection: doctrine
  tableName: language
  columns:
    idlang:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    descriptor:
      type: string(2)
      fixed: true
      unsigned: false
      primary: false
      default: ''
      notnull: true
      autoincrement: false
Project:
  connection: doctrine
  tableName: project
  columns:
    idproject:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Text:
      local: idproject
      foreign: idproject
      type: many
Text:
  connection: doctrine
  tableName: text
  actAs:
    I18n:
      fields: [paragraph, status]
  columns:
    idtext:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    paragraph:
      type: string(650)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    app:
      type: boolean
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    web:
      type: boolean
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    destinationfile:
      type: string(250)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    status:
      type: boolean
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    idproject:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    created:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    updated:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Project:
      local: idproject
      foreign: idproject
      type: one
